### PR TITLE
fixed typo and added two tests

### PR DESCRIPTION
**Pull request by artempervin**
- fixed typo
- added tests for noexcept and generic lambda

### CODE REVIEW

**Comment by sloede** [comment]
Hi Artem, thanks for your contributions. Since generic lambdas were not introduced until C++14, the check produces a false-negative for all compilers I've tested. Once you remove the `lambda-generic.cpp` file from the PR, I'll happily merge your branch.

**Comment by artempervin** [comment]
Hi Michael.

I've removed lambda-generic test now.

**Comment by sloede** [comment]
Thanks a lot!

**Comment by s7726** [comment]
A little hijack here... This is an awesome suite for checking compatibility. Does it make sense to rename it and provide some kind of command line or config option for the level you want to check? C++11, C++14, C++17, etc. Having one suite to test various levels would be awesome.

**Comment by sloede** [comment]
@s7726 this would be a great idea! Unfortunately, I do not have time to set up any new tests for C++14 or greater. If somebody is interested, though, I could rename the project and set up the infrastructure such that the suite of tests to run can be selected at configure time. Are you up for it?

**Pull request merged**
